# Generated by Django 4.2.4 on 2023-11-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myshorter', '0009_rename_acrive_shortyurl_active_remove_shortyurl_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('timstamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('url_shorty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshorter.shortyurl')),
            ],
        ),
    ]
