# Generated by Django 4.2.6 on 2023-11-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortyurl',
            name='shotcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
