# Generated by Django 4.2.6 on 2023-11-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshorter', '0004_alter_shortyurl_shotcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortyurl',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
