# Generated by Django 4.2.6 on 2023-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshorter', '0007_shortyurl_acrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortyurl',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
