# Generated by Django 4.2.6 on 2023-11-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshorter', '0008_shortyurl_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortyurl',
            old_name='acrive',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='shortyurl',
            name='slug',
        ),
    ]
